#!/bin/bash -x
yum install -y httpd
apachectl start
systemctl enable  httpd
systemctl start  httpd
firewall-offline-cmd --add-service=http
systemctl enable  firewalld
systemctl restart  firewalld
sh -c "echo 'Hello World from:' `hostname` >/var/www/html/index.html"
